[tool.poetry]
name = 'canonicalwebteam.store-api'
version = '2.0.2'
description = ''
authors = ['Canonical Web Team <webteam@canonical.com>']
license = 'LGPL-3.0'
readme = 'README.md'

[[tool.poetry.packages]]
include = 'canonicalwebteam'

[tool.poetry.dependencies]
python = '^3.6'
requests = '^2.22'
vcrpy-unittest = '^0.1.7'
coverage = '^5.0'

[tool.poetry.dev-dependencies]
pytest = '^5.3'

[build-system]
requires = ['poetry>=0.12']
build-backend = 'poetry.masonry.api'
