[tool.poetry]
name = "canonicalwebteam.store-api"
version = "0.1.0"
description = ""
authors = ["Canonical Web Team <webteam@canonical.com>"]
license = "LGPL-3.0"
readme = "README.md"

packages = [
    { include = "canonicalwebteam" }
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22"
pybreaker = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

